In [2]:
import numpy as np

In [4]:
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [6]:
a2=np.array([[1,2,3],[4,5,6]]) 
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
type(a1)

numpy.ndarray

In [14]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [15]:
np.shape(a1)

(3,)

In [16]:
np.shape(a2)

(2, 3)

In [17]:
np.shape(a3)

(1, 6, 3)

In [19]:
a1.ndim

1

In [22]:
a2.ndim 


2

In [23]:
a3.ndim

3

In [24]:
a1.size ,a2.size , a3.size

(3, 6, 18)

In [33]:
import pandas as pd
data =pd.DataFrame(a2)
data


0  1  2
0  1  2  3
1  4  5  6

In [6]:
once=np.ones((10,2))
once

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
zeros=np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
# You can change the datatype with .astype()
once.astype(int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [10]:
once.astype(str)

array([['1.0', '1.0'],
       ['1.0', '1.0'],
       ['1.0', '1.0'],
       ['1.0', '1.0'],
       ['1.0', '1.0'],
       ['1.0', '1.0'],
       ['1.0', '1.0'],
       ['1.0', '1.0'],
       ['1.0', '1.0'],
       ['1.0', '1.0']], dtype='<U32')

In [11]:
zeros.dtype


dtype('float64')

In [16]:
#random int
random=np.random.randint(10,size=(4,2))
random

array([[2, 9],
       [7, 3],
       [2, 3],
       [0, 0]], dtype=int32)

In [19]:
random.dtype

dtype('int32')

In [24]:
arrange= np.arange(0,10,2)
arrange

array([0, 2, 4, 6, 8])

In [31]:
#random folt
rand=np.random.random((5,3))
rand

array([[0.19932385, 0.17321363, 0.76949085],
       [0.31308617, 0.73239785, 0.2175977 ],
       [0.54684312, 0.02708357, 0.90689196],
       [0.79748265, 0.69400321, 0.06274785],
       [0.30668684, 0.22746556, 0.41953249]])

In [30]:
ran=np.random.rand(5,3)
ran

array([[0.65811361, 0.48890465, 0.84709081],
       [0.7756824 , 0.46116173, 0.85781754],
       [0.22358298, 0.59774549, 0.96712624],
       [0.84340178, 0.4287982 , 0.12888378],
       [0.75863778, 0.15549515, 0.73543936]])

In [34]:
np.random.seed(0)
rand=np.random.randint(10,size=(5,3))
rand

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [38]:
np.random.seed(0)
randno=np.random.randint(10,size=(2,3,4,5))
randno

array([[[[5, 0, 3, 3, 7],
         [9, 3, 5, 2, 4],
         [7, 6, 8, 8, 1],
         [6, 7, 7, 8, 1]],

        [[5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3],
         [3, 3, 7, 0, 1]],

        [[9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6],
         [8, 4, 1, 4, 9]]],


       [[[8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4],
         [4, 6, 4, 4, 3]],

        [[4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5],
         [0, 1, 2, 4, 2]],

        [[0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3],
         [2, 3, 4, 1, 2]]]], dtype=int32)

In [39]:
randno[:,:,:,4]

array([[[7, 4, 1, 1],
        [4, 0, 3, 1],
        [7, 0, 6, 9]],

       [[9, 2, 4, 3],
        [3, 1, 5, 2],
        [7, 7, 3, 2]]], dtype=int32)

In [37]:
randno[:,:,:,3]

array([[[8, 9, 5, 1],
        [0, 4, 2, 5],
        [4, 7, 7, 9]],

       [[4, 4, 0, 0],
        [4, 0, 2, 3],
        [1, 6, 0, 3]]], dtype=int32)