In [1]:
import numpy as np

In [4]:
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [6]:
a2=np.array([[1,2,3],[4,5,6]]) 
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
type(a1)

numpy.ndarray

In [14]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [15]:
np.shape(a1)

(3,)

In [16]:
np.shape(a2)

(2, 3)

In [17]:
np.shape(a3)

(1, 6, 3)

In [19]:
a1.ndim

1

In [22]:
a2.ndim 


2

In [23]:
a3.ndim

3

In [24]:
a1.size ,a2.size , a3.size

(3, 6, 18)

In [33]:
import pandas as pd
data =pd.DataFrame(a2)
data


0  1  2
0  1  2  3
1  4  5  6